version: '3.3'
services:
  nginx:
    image: adixonfr/nginx-malteurop:v1.0
    build:
      context: ../../Sites/MaltEurop/MaltEurop-Frontend/
      dockerfile: Dockerfile-Prod
    depends_on:
      - maltdb
    ports:
    - "80:80"
    - "443:443"
    networks:
    - frontend
    restart: on-failure
  sails:
    image: adixonfr/sails-malteurop:v1.0
    build:
      context: ../../Sites/MaltEurop/MaltEurop-Backend/
      dockerfile: Dockerfile-Prod
    depends_on:
    - maltdb
    command: pm2-docker start --env "prod" app.js
    ports:
    - "1337:1337"
    networks:
    - frontend
    - backend
    restart: on-failure
  maltdb:
    image: mysql:latest
    build: ./mysql
    ports:
    - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
    - backend
    volumes:
    - datavolume:/var/lib/mysql
    restart: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  frontend:
  backend:
volumes:
  datavolume:
